export const sampleTrades = [
  {
    id: "sample-1",
    userId: "mock-user-1",
    date: "2026-08-03T13:30:00.000Z",
    instrument: "EURUSD",
    market: "FOREX",
    session: "New York",
    direction: "LONG",
    timeframe: "15m",
    entryPrice: 1.0850,
    stopLoss: 1.0830,
    takeProfit: 1.0910,
    exitPrice: 1.0910,
    positionSize: 2.0,
    riskAmount: 400,
    riskPercentage: 1.0,
    plannedRR: 3.0,
    actualR: 3.0,
    pnl: 1200,
    result: "WIN",
    grade: "A_PLUS",
    setup: "Liquidity Sweep + FVG",
    htfBias: "Bullish",
    notes: "Perfect NY session entry following Asian low sweep.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [],
  },
  {
    id: "sample-2",
    userId: "mock-user-1",
    date: "2026-08-05T08:15:00.000Z",
    instrument: "NAS100",
    market: "INDICES",
    session: "London",
    direction: "SHORT",
    timeframe: "5m",
    entryPrice: 19800,
    stopLoss: 19850,
    takeProfit: 19680,
    exitPrice: 19850,
    positionSize: 1.0,
    riskAmount: 500,
    riskPercentage: 1.0,
    plannedRR: 2.4,
    actualR: -1.0,
    pnl: -500,
    result: "LOSS",
    grade: "B",
    setup: "MSS + Displacement",
    htfBias: "Bearish",
    notes: "Stopped out as momentum reversed into London open.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [],
  },
  {
    id: "sample-3",
    userId: "mock-user-1",
    date: "2026-08-10T14:00:00.000Z",
    instrument: "GBPUSD",
    market: "FOREX",
    session: "New York",
    direction: "LONG",
    timeframe: "15m",
    entryPrice: 1.2720,
    stopLoss: 1.2700,
    takeProfit: 1.2770,
    exitPrice: 1.2770,
    positionSize: 1.5,
    riskAmount: 300,
    riskPercentage: 1.0,
    plannedRR: 2.5,
    actualR: 2.5,
    pnl: 750,
    result: "WIN",
    grade: "A",
    setup: "Order Block Bounce",
    htfBias: "Bullish",
    notes: "Clean target hit right at London close overlap.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [],
  },
  {
    id: "sample-4",
    userId: "mock-user-1",
    date: "2026-08-14T09:30:00.000Z",
    instrument: "XAUUSD",
    market: "COMMODITIES",
    session: "London",
    direction: "LONG",
    timeframe: "15m",
    entryPrice: 2420.0,
    stopLoss: 2412.0,
    takeProfit: 2436.0,
    exitPrice: 2432.0,
    positionSize: 1.0,
    riskAmount: 400,
    riskPercentage: 1.0,
    plannedRR: 2.0,
    actualR: 1.5,
    pnl: 600,
    result: "WIN",
    grade: "A_PLUS",
    setup: "Discount FVG Retracement",
    htfBias: "Bullish",
    notes: "Closed early prior to high-impact CPI release.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [],
  },
  {
    id: "sample-5",
    userId: "mock-user-1",
    date: "2026-08-20T10:00:00.000Z",
    instrument: "EURUSD",
    market: "FOREX",
    session: "London",
    direction: "SHORT",
    timeframe: "15m",
    entryPrice: 1.0900,
    stopLoss: 1.0920,
    takeProfit: 1.0850,
    exitPrice: 1.0900,
    positionSize: 2.0,
    riskAmount: 400,
    riskPercentage: 1.0,
    plannedRR: 2.5,
    actualR: 0.0,
    pnl: 0,
    result: "BREAKEVEN",
    grade: "B_PLUS",
    setup: "Liquidity Sweep",
    htfBias: "Bearish",
    notes: "Moved SL to breakeven after 1R reached.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [],
  },
];
