import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting development seed script...");

  // Clean existing demo data
  await prisma.tradeImage.deleteMany({});
  await prisma.trade.deleteMany({});
  await prisma.backtestTrade.deleteMany({});
  await prisma.checklistItem.deleteMany({});
  await prisma.checklist.deleteMany({});
  await prisma.tradingRule.deleteMany({});
  await prisma.propAccount.deleteMany({});
  await prisma.goal.deleteMany({});
  await prisma.user.deleteMany({});

  const passwordHash = await bcrypt.hash("password123", 10);

  const demoUser = await prisma.user.create({
    data: {
      name: "Abel Trade",
      email: "trader@axumify.com",
      passwordHash,
      timezone: "UTC-3",
      currency: "USD",
    },
  });

  console.log(`👤 Created Demo User: ${demoUser.email} (ID: ${demoUser.id})`);

  // Sample Trades
  const tradesData = [
    {
      date: new Date("2026-08-26T14:30:00Z"),
      instrument: "EURUSD",
      market: "FOREX",
      session: "New York",
      direction: "LONG",
      timeframe: "15m",
      entryPrice: 1.08500,
      stopLoss: 1.08350,
      takeProfit: 1.08950,
      exitPrice: 1.08950,
      positionSize: 2.0,
      riskAmount: 300,
      riskPercentage: 1.0,
      plannedRR: 3.0,
      actualR: 1.8,
      pnl: 540.0,
      result: "WIN",
      grade: "A_PLUS",
      ictConcepts: JSON.stringify(["Sell-side liquidity", "MSS", "Displacement", "FVG", "OTE"]),
      setup: "Liquidity Sweep + FVG Retracement",
      customTags: JSON.stringify(["ICT Classic", "High Probability"]),
      htfBias: "Bullish",
      marketCondition: "Trending",
      liquidityTarget: "Previous Day High (1.08950)",
      entryModel: "15m FVG Entry",
      confirmation: "1m MSS + Displacement",
      invalidation: "Below Asian Low (1.08350)",
      targetReason: "PDH + Liquidity Pool",
      reasonForEntry: "Price swept Asian Low, created sharp MSS with displacement leaving a 15m FVG.",
      psychConfidence: 5,
      psychPatience: 5,
      psychFear: 1,
      psychGreed: 1,
      psychFOMO: 1,
      psychRevenge: 1,
      psychDiscipline: 5,
      psychStress: 1,
      emotionBefore: "Calm & Focused",
      emotionDuring: "Patient",
      emotionAfter: "Confident",
      followedPlan: true,
      brokeRule: false,
      enteredTooEarly: false,
      movedSL: false,
      closedEarly: false,
      overtraded: false,
      mistakes: JSON.stringify([]),
      positives: JSON.stringify(["Followed plan", "Waited for confirmation", "Good risk management", "Good execution"]),
      notes: "Flawless ICT setup. Entry executed exactly at the top of 15m FVG after NY open liquidity grab.",
    },
    {
      date: new Date("2026-08-25T13:45:00Z"),
      instrument: "NAS100",
      market: "INDICES",
      session: "New York",
      direction: "SHORT",
      timeframe: "5m",
      entryPrice: 19850.0,
      stopLoss: 19900.0,
      takeProfit: 19700.0,
      exitPrice: 19700.0,
      positionSize: 1.5,
      riskAmount: 250,
      riskPercentage: 1.0,
      plannedRR: 3.0,
      actualR: 3.0,
      pnl: 750.0,
      result: "WIN",
      grade: "A",
      ictConcepts: JSON.stringify(["Buy-side liquidity", "Order Block", "BOS", "Displacement"]),
      setup: "Order Block Rejection",
      customTags: JSON.stringify(["Indices", "NY Silver Bullet"]),
      htfBias: "Bearish",
      marketCondition: "Ranging to Bearish",
      liquidityTarget: "Sell-side Liquidity (19700)",
      entryModel: "5m Order Block",
      confirmation: "CHoCH on 1m",
      invalidation: "Above 19900 high",
      targetReason: "Equal Lows Target",
      reasonForEntry: "NY open pushed up into 1h Order Block, swept London High and rejected with heavy displacement.",
      psychConfidence: 4,
      psychPatience: 4,
      psychFear: 2,
      psychGreed: 1,
      psychFOMO: 1,
      psychRevenge: 1,
      psychDiscipline: 5,
      psychStress: 2,
      emotionBefore: "Neutral",
      emotionDuring: "Calm",
      emotionAfter: "Satisfied",
      followedPlan: true,
      brokeRule: false,
      enteredTooEarly: false,
      movedSL: false,
      closedEarly: false,
      overtraded: false,
      mistakes: JSON.stringify([]),
      positives: JSON.stringify(["Followed plan", "Good exit", "Session rules"]),
      notes: "Precision rejection from 1h OB. Took full profit at EQL.",
    },
    {
      date: new Date("2026-08-24T08:15:00Z"),
      instrument: "GBPUSD",
      market: "FOREX",
      session: "London",
      direction: "LONG",
      timeframe: "15m",
      entryPrice: 1.30200,
      stopLoss: 1.30000,
      takeProfit: 1.30800,
      exitPrice: 1.30000,
      positionSize: 1.0,
      riskAmount: 200,
      riskPercentage: 0.8,
      plannedRR: 3.0,
      actualR: -1.0,
      pnl: -200.0,
      result: "LOSS",
      grade: "B",
      ictConcepts: JSON.stringify(["Asian Low", "FVG"]),
      setup: "FVG Retracement",
      customTags: JSON.stringify(["London Session"]),
      htfBias: "Bullish",
      marketCondition: "Volatile",
      liquidityTarget: "London High",
      entryModel: "15m FVG",
      confirmation: "MSS",
      invalidation: "Below 1.30000",
      targetReason: "London High",
      reasonForEntry: "London open expansion into FVG.",
      psychConfidence: 3,
      psychPatience: 2,
      psychFear: 3,
      psychGreed: 2,
      psychFOMO: 2,
      psychRevenge: 1,
      psychDiscipline: 3,
      psychStress: 3,
      emotionBefore: "Slightly Hesitant",
      emotionDuring: "Anxious",
      emotionAfter: "Accepting",
      followedPlan: true,
      brokeRule: false,
      enteredTooEarly: true,
      movedSL: false,
      closedEarly: false,
      overtraded: false,
      mistakes: JSON.stringify(["Early entry", "No confirmation"]),
      positives: JSON.stringify(["Good risk management"]),
      notes: "Entered before lower timeframe MSS was fully confirmed. Stop loss hit clean.",
    },
    {
      date: new Date("2026-08-21T15:00:00Z"),
      instrument: "XAUUSD",
      market: "COMMODITIES",
      session: "New York",
      direction: "LONG",
      timeframe: "15m",
      entryPrice: 2510.0,
      stopLoss: 2500.0,
      takeProfit: 2540.0,
      exitPrice: 2535.0,
      positionSize: 0.5,
      riskAmount: 250,
      riskPercentage: 1.0,
      plannedRR: 3.0,
      actualR: 2.5,
      pnl: 625.0,
      result: "WIN",
      grade: "A",
      ictConcepts: JSON.stringify(["Liquidity sweep", "Breaker Block", "Displacement"]),
      setup: "Breaker Block + Gold Expansion",
      customTags: JSON.stringify(["Gold", "NY PM"]),
      htfBias: "Bullish",
      marketCondition: "Strong Uptrend",
      liquidityTarget: "All Time Highs",
      entryModel: "Breaker Block",
      confirmation: "1m Displacement",
      invalidation: "2500 level",
      targetReason: "2540 Liquidity Pool",
      reasonForEntry: "Sweep of London Low followed by massive displacement forming a Breaker Block.",
      psychConfidence: 5,
      psychPatience: 5,
      psychFear: 1,
      psychGreed: 1,
      psychFOMO: 1,
      psychRevenge: 1,
      psychDiscipline: 5,
      psychStress: 1,
      emotionBefore: "Calm",
      emotionDuring: "Confident",
      emotionAfter: "Happy",
      followedPlan: true,
      brokeRule: false,
      enteredTooEarly: false,
      movedSL: false,
      closedEarly: true,
      overtraded: false,
      mistakes: JSON.stringify([]),
      positives: JSON.stringify(["Followed plan", "Waited for confirmation", "Good execution"]),
      notes: "Secured +2.5R manually at 2535 resistance ahead of high-impact news.",
    },
    {
      date: new Date("2026-08-20T10:30:00Z"),
      instrument: "EURUSD",
      market: "FOREX",
      session: "London",
      direction: "SHORT",
      timeframe: "15m",
      entryPrice: 1.08900,
      stopLoss: 1.09050,
      takeProfit: 1.08450,
      exitPrice: 1.08500,
      positionSize: 1.8,
      riskAmount: 270,
      riskPercentage: 1.0,
      plannedRR: 3.0,
      actualR: 2.66,
      pnl: 720.0,
      result: "WIN",
      grade: "A_PLUS",
      ictConcepts: JSON.stringify(["Asian High", "MSS", "IFVG", "Order Block"]),
      setup: "Asian High Sweep + IFVG",
      customTags: JSON.stringify(["ICT Classic"]),
      htfBias: "Bearish",
      marketCondition: "Downtrend",
      liquidityTarget: "Asian Low",
      entryModel: "IFVG Re-entry",
      confirmation: "5m MSS",
      invalidation: "Above Asian High",
      targetReason: "Liquidity Pool below Asian Low",
      reasonForEntry: "London opened, pushed 15 pips above Asian High, immediately reversed into IFVG.",
      psychConfidence: 4,
      psychPatience: 5,
      psychFear: 1,
      psychGreed: 1,
      psychFOMO: 1,
      psychRevenge: 1,
      psychDiscipline: 5,
      psychStress: 1,
      emotionBefore: "Patient",
      emotionDuring: "Relaxed",
      emotionAfter: "Satisfied",
      followedPlan: true,
      brokeRule: false,
      enteredTooEarly: false,
      movedSL: false,
      closedEarly: false,
      overtraded: false,
      mistakes: JSON.stringify([]),
      positives: JSON.stringify(["Waited for confirmation", "Followed plan", "Good exit"]),
      notes: "Classic Asian High sweep setup.",
    },
    {
      date: new Date("2026-08-19T14:00:00Z"),
      instrument: "NAS100",
      market: "INDICES",
      session: "New York",
      direction: "LONG",
      timeframe: "5m",
      entryPrice: 19600.0,
      stopLoss: 19560.0,
      takeProfit: 19720.0,
      exitPrice: 19600.0,
      positionSize: 1.2,
      riskAmount: 200,
      riskPercentage: 0.8,
      plannedRR: 3.0,
      actualR: 0.0,
      pnl: 0.0,
      result: "BREAKEVEN",
      grade: "B_PLUS",
      ictConcepts: JSON.stringify(["Discount", "FVG"]),
      setup: "Discount FVG",
      customTags: JSON.stringify(["Indices"]),
      htfBias: "Bullish",
      marketCondition: "Consolidating",
      liquidityTarget: "NY Open High",
      entryModel: "5m FVG",
      confirmation: "1m CHoCH",
      invalidation: "Below 19560",
      targetReason: "NY High",
      reasonForEntry: "Retracement to 62% OTE into 5m FVG.",
      psychConfidence: 3,
      psychPatience: 4,
      psychFear: 2,
      psychGreed: 2,
      psychFOMO: 1,
      psychRevenge: 1,
      psychDiscipline: 4,
      psychStress: 2,
      emotionBefore: "Neutral",
      emotionDuring: "Patient",
      emotionAfter: "Neutral",
      followedPlan: true,
      brokeRule: false,
      enteredTooEarly: false,
      movedSL: true,
      closedEarly: false,
      overtraded: false,
      mistakes: JSON.stringify([]),
      positives: JSON.stringify(["Moved SL to breakeven after +1.5R"]),
      notes: "Price pushed up +1.8R, moved stop to breakeven, market reversed and stopped me out at zero loss.",
    },
    {
      date: new Date("2026-08-18T13:30:00Z"),
      instrument: "BTCUSD",
      market: "CRYPTO",
      session: "New York",
      direction: "SHORT",
      timeframe: "1h",
      entryPrice: 64500.0,
      stopLoss: 65200.0,
      takeProfit: 62400.0,
      exitPrice: 65200.0,
      positionSize: 0.5,
      riskAmount: 350,
      riskPercentage: 1.2,
      plannedRR: 3.0,
      actualR: -1.0,
      pnl: -350.0,
      result: "LOSS",
      grade: "C",
      ictConcepts: JSON.stringify(["Equal Highs"]),
      setup: "Equal Highs Fade",
      customTags: JSON.stringify(["Crypto"]),
      htfBias: "Bearish",
      marketCondition: "High Volatility",
      liquidityTarget: "62400 Low",
      entryModel: "1h OB",
      confirmation: "None",
      invalidation: "65200",
      targetReason: "Liquidity Pool",
      reasonForEntry: "Anticipated rejection from 64500 without waiting for MSS confirmation.",
      psychConfidence: 2,
      psychPatience: 1,
      psychFear: 4,
      psychGreed: 3,
      psychFOMO: 4,
      psychRevenge: 2,
      psychDiscipline: 2,
      psychStress: 4,
      emotionBefore: "Anxious / FOMO",
      emotionDuring: "Nervous",
      emotionAfter: "Frustrated",
      followedPlan: false,
      brokeRule: true,
      enteredTooEarly: true,
      movedSL: false,
      closedEarly: false,
      overtraded: true,
      mistakes: JSON.stringify(["FOMO", "No confirmation", "Oversized position", "Ignored HTF bias"]),
      positives: JSON.stringify([]),
      notes: "Classic FOMO trade. Entered crypto market during choppy price action without confirmation.",
    },
    {
      date: new Date("2026-08-17T09:00:00Z"),
      instrument: "EURUSD",
      market: "FOREX",
      session: "London",
      direction: "LONG",
      timeframe: "15m",
      entryPrice: 1.08100,
      stopLoss: 1.07950,
      takeProfit: 1.08550,
      exitPrice: 1.08550,
      positionSize: 2.0,
      riskAmount: 300,
      riskPercentage: 1.0,
      plannedRR: 3.0,
      actualR: 3.0,
      pnl: 900.0,
      result: "WIN",
      grade: "A_PLUS",
      ictConcepts: JSON.stringify(["Asian Low", "MSS", "Displacement", "FVG"]),
      setup: "Asian Low Sweep + FVG",
      customTags: JSON.stringify(["ICT Classic"]),
      htfBias: "Bullish",
      marketCondition: "Trending Up",
      liquidityTarget: "Previous Day High",
      entryModel: "15m FVG",
      confirmation: "5m MSS",
      invalidation: "Below 1.07950",
      targetReason: "1.08550 PDH",
      reasonForEntry: "Asian low swept cleanly at London open with immediate bullish displacement.",
      psychConfidence: 5,
      psychPatience: 5,
      psychFear: 1,
      psychGreed: 1,
      psychFOMO: 1,
      psychRevenge: 1,
      psychDiscipline: 5,
      psychStress: 1,
      emotionBefore: "Calm",
      emotionDuring: "Patient",
      emotionAfter: "Confident",
      followedPlan: true,
      brokeRule: false,
      enteredTooEarly: false,
      movedSL: false,
      closedEarly: false,
      overtraded: false,
      mistakes: JSON.stringify([]),
      positives: JSON.stringify(["Followed plan", "Waited for confirmation", "Good execution"]),
      notes: "Full target hit in 45 minutes.",
    }
  ];

  for (const t of tradesData) {
    await prisma.trade.create({
      data: {
        userId: demoUser.id,
        ...t,
      },
    });
  }
  console.log(`✅ Seeded ${tradesData.length} live trading records.`);

  // Sample Prop Firm Account
  const propAccount = await prisma.propAccount.create({
    data: {
      userId: demoUser.id,
      firmName: "FTMO $100K Challenge",
      accountSize: 100000.0,
      startingBalance: 100000.0,
      currentBalance: 103250.0,
      profitTarget: 10000.0,
      maxDailyLoss: 5000.0,
      maxTotalDrawdown: 10000.0,
      currentDrawdown: 450.0,
      status: "EVALUATION",
    },
  });
  console.log(`🏆 Seeded Prop Account: ${propAccount.firmName}`);

  // Sample Pre-Market Checklists
  const checklist = await prisma.checklist.create({
    data: {
      userId: demoUser.id,
      title: "Pre-Market Daily Checklist",
      category: "PRE_MARKET",
      items: {
        create: [
          { text: "Check Economic High Impact News Calendar", checked: true, order: 1 },
          { text: "Determine Daily & 4h Higher Timeframe Bias", checked: true, order: 2 },
          { text: "Mark Previous Day High (PDH) & Previous Day Low (PDL)", checked: true, order: 3 },
          { text: "Mark Asian Session High & Low Range", checked: true, order: 4 },
          { text: "Identify Key Liquidity Pools (EQH / EQL)", checked: true, order: 5 },
          { text: "Wait for Session Open (London 8:00 AM / NY 9:30 AM)", checked: true, order: 6 },
          { text: "Confirm Liquidity Sweep + Lower Timeframe MSS", checked: false, order: 7 },
          { text: "Identify FVG or Order Block Entry Zone", checked: false, order: 8 },
          { text: "Verify Position Risk ≤ 1.0% & Planned RR ≥ 1:2.5", checked: false, order: 9 },
        ],
      },
    },
  });
  console.log(`📋 Seeded Checklist: ${checklist.title}`);

  // Sample Trading Rules
  const rules = [
    { text: "Never risk more than 1.0% per trade under any circumstances.", category: "RISK", isActive: true },
    { text: "Minimum Planned Risk-to-Reward ratio must be at least 1:2.5.", category: "EXECUTION", isActive: true },
    { text: "Must have HTF Bias + Liquidity Sweep + MSS + FVG confirmation before entry.", category: "EXECUTION", isActive: true },
    { text: "Stop trading for the day after 2 consecutive losing trades.", category: "PSYCHOLOGY", isActive: true },
    { text: "Never move Stop Loss further away once trade is active.", category: "PSYCHOLOGY", isActive: true },
    { text: "No trading 15 minutes before or after NFP, CPI, or FOMC news.", category: "RISK", isActive: true },
  ];

  for (const r of rules) {
    await prisma.tradingRule.create({
      data: {
        userId: demoUser.id,
        ...r,
      },
    });
  }
  console.log(`📜 Seeded ${rules.length} Trading Rules.`);

  // Sample Goals
  const goals = [
    { title: "Achieve +20R Net Return", targetValue: 20.0, currentValue: 12.16, unit: "R", isCompleted: false },
    { title: "Log 50 ICT Setups in Journal", targetValue: 50.0, currentValue: 8.0, unit: "Trades", isCompleted: false },
    { title: "Maintain 65%+ Win Rate", targetValue: 65.0, currentValue: 70.6, unit: "%", isCompleted: true },
    { title: "Pass FTMO Step 1 Target ($10,000)", targetValue: 10000.0, currentValue: 3250.0, unit: "$", isCompleted: false },
  ];

  for (const g of goals) {
    await prisma.goal.create({
      data: {
        userId: demoUser.id,
        ...g,
      },
    });
  }
  console.log(`🎯 Seeded ${goals.length} Goals.`);

  console.log("🚀 Seed complete!");
}

main()
  .catch((e) => {
    console.error("❌ Seed script error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
